Algoritmo "COVID-19"


Var
      c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, m7, m8: real
       media, medianac, medianam : real
Inicio

      escreval ("  País  ", "           Casos", "       Mortes  ")
      escreval ("---------------------------------------")
      escreval ("  EUA  ", "           5.331.169  ", "  168.429" )
      escreval ("---------------------------------------")
      escreval ("  Brasil  ", "        3.123.109  ", "  103.421  ")
      escreval ("---------------------------------------")
      escreval ("  Índia  ", "         2.395.471  ", "  47.138  ")
      escreval ("---------------------------------------")
      escreval ("  Rússia  ", "        902.701  ", "    15.260  ")
      escreval ("---------------------------------------")
      escreval ("  África do Sul  ", " 566.109  ", "    10.751  ")
      escreval ("---------------------------------------")
      escreval ("  México   ", "       492.522  ", "    53.929 ")
      escreval ("---------------------------------------")
      escreval ("  Peru  ", "          489.680  ", "    21.501  ")
      escreval ("---------------------------------------")
      escreval ("  Colômbia  ", "      410.453  ", "    13.474  ")
      escreval ("---------------------------------------")
      escreval ("  Chile  ", "         378.168  ", "    10.205  ")
      escreval ("---------------------------------------")
      escreval ("  Espanha  ", "       376.864  ", "    28.581  ")
      escreval ("---------------------------------------")
      escreval ("  Irã  ", "           333.699  ", "    18.988  ")
      escreval ("---------------------------------------")
      escreval ("  Reino Unido  ", "   313.798  ", "    46.706   ")
      escreval ("---------------------------------------")
      escreval ("  Árabia Saudita  ", "293.037  ", "    3.269  ")
      escreval ("---------------------------------------")
      escreval ("  Paquistão  ", "     285.921  ", "    6.129   ")
      escreval ("---------------------------------------")
      escreval ("  Bangladesh  ", "    266.498  ", "    3.513  ")
      
      c1 <-  5331169
      c2 <-  3123109
      c3 <-  2395471
      c4 <-  902701
      c5 <-  566109
      c6 <-  492522
      c7 <-  489680
      c8 <-  410453
      c9 <-  378168
      c10 <- 376864
      c11 <- 333699
      c12 <- 313798
      c13 <- 293037
      c14 <- 285921
      c15 <- 266498
      
      m7 <-  21501
      m8 <-  13475
      //quando coloco os valores com ponto, o programa não roda

      media <- ((c1+c2+c3+c4+c5+c6+c7+c8+c9+c10+c11+c12+c13+c14+c15)/15)
      escreval ("A média de casos no mundo é: ", media)
      
      medianac <- ((c7+c8)/2)
      escreval ("A mediana de casos no mundo é: ", medianac)
      
      medianam <- ((m7+m8)/2)
      escreval ("A mediana de mortes no mundo é: ", medianam)
      

      
      





      



Fimalgoritmo