Algoritmo "Número maior"

Var
    valor1, valor2, valor3 : real

Inicio
   escreval ("Vamos informar a ordem crescente")
   escreval ("Informe três valores")
   leia (valor1)
   leia (valor2)
   leia (valor3)

   se valor1>valor2>valor3 entao
       escreval (valor3,valor2,valor1)
   senao
       se valor3>valor2>valor1
          escreval (valor1,valor2,valor3)
       senao
          se
       fimse
   fimse


Fimalgoritmo