Algoritmo "QUESTAO2"


Var
      n1, n2 : real


Inicio
      escreval ("Informe o primeiro valor")
      leia (n1)
      escreval ("Informe o segundo valor")
      leia (n2)
      escreval ("O primeiro valor foi: ", n1)
      escreval ("O segundo valor foi: ", n2)
      escreva ("Então, ")

      se n1>n2 entao
         escreva ("o 1° valor é maior e o 2° valor é menor")
      senao
           escreva ("o 2° valor é maior e o 1° valor é menor")
      fimse


Fimalgoritmo